# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

[[templates]]
path = "logical-component.html.j2"
name = "Logical Components"
id = "logical-component"
description = "Specifies a logical component. This is a ported template from a prototype project."
flags = ["experimental"]
scope = { type = "LogicalComponent", below = "la" }

[[templates]]
path = "logical-interface.html.j2"
id = "logical-interface"
name = "Logical Interfaces"
description = "Defines interfaces between actors and logical system components"
flags = ["experimental"]
scope = { type = "ComponentExchange", below = "la" }

[[templates]]
path = "FIS.html.j2"
id = "functional-interface-specification"
name = "Functional Interface Specification"
description = "Defines functional interfaces between logical components (subsystems) and actors"
flags = ["experimental"]
scope = { type = "ComponentExchange", below = "la" }

[[templates]]
path = "logical-function.html.j2"
id = "logical-function"
name = "Logical Functions"
description = "Defines function of a logical system component or an actor"
scope = { type = "LogicalFunction", below = "la" }

[[templates]]
path = "logical-state.html.j2"
id = "logical-component-mode"
name = "Logical Component Modes"
description = "Defines states and modes of a system component or an actor"
flags = ["experimental"]
scope = { type = "Mode", below = "la" }

[[templates]]
path = "logical-state.html.j2"
id = "logical-component-state"
name = "Logical Component States"
description = "Defines states and modes of a system component or an actor"
flags = ["experimental"]
scope = { type = "State", below = "la" }
